/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/assets/index" |
       "/pages/currency-records/index" |
       "/pages/equity-records/index" |
       "/pages/login/change-password" |
       "/pages/login/index" |
       "/pages/login/password" |
       "/pages/login/reset-password" |
       "/pages/my/alipay-accounts" |
       "/pages/my/alipay-payment-setting" |
       "/pages/my/announcement-detail" |
       "/pages/my/announcements" |
       "/pages/my/bank-account-apply" |
       "/pages/my/bank-cards" |
       "/pages/my/customer-service" |
       "/pages/my/identity-verify" |
       "/pages/my/index" |
       "/pages/my/reset-password" |
       "/pages/my/reset-withdraw-password" |
       "/pages/my/settings" |
       "/pages/my/wallet" |
       "/pages/my/wechat-payment-setting" |
       "/pages/my/withdraw" |
       "/pages/payment/index" |
       "/pages/register/captcha" |
       "/pages/register/index" |
       "/pages/team/index" |
       "/pages/team/invite-poster" |
       "/pages/trading/exchange" |
       "/pages/trading/index" |
       "/pages/trading/records" |
       "/pages/trading/trade-detail" |
       "/pages/transfer/alipay" |
       "/pages/transfer/bank" |
       "/pages/transfer/index" |
       "/pages/transfer/phone-pay" |
       "/pages/transfer/wechat" |
       "/pages/verification/index" |
       "/pages/webview/index" |
       "/uni_modules/uni-upgrade-center-app/pages/upgrade-popup";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/trading/index" | "/pages/assets/index" | "/pages/my/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
